version: '3.8'

services:

  backend:
    build: app
    ports:
      - "80:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: app
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7-alpine

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - worker
